name: test

on:
  push:
    branches:
      - master
      - develop
  pull_request:

env:
  FOUNDRY_PROFILE: ci
  TEST_RPC_URL: ${{ secrets.TEST_RPC_URL }}
  TEST_RPC_URL_ETH: ${{ secrets.TEST_RPC_URL_ETH }}
  TEST_SAFE_SINGLETON_ETH: ${{ secrets.TEST_SAFE_SINGLETON_ETH }}
  TEST_SAFE_PROXY_FACTORY_ETH: ${{ secrets.TEST_SAFE_PROXY_FACTORY_ETH }}
  TEST_RPC_URL_POLYGON: ${{ secrets.TEST_RPC_URL_POLYGON }}
  TEST_SAFE_SINGLETON_POLYGON: ${{ secrets.TEST_SAFE_SINGLETON_POLYGON }}
  TEST_SAFE_PROXY_FACTORY_POLYGON: ${{ secrets.TEST_SAFE_PROXY_FACTORY_POLYGON }}
  TEST_RPC_URL_CELO: ${{ secrets.TEST_RPC_URL_CELO }}
  TEST_SAFE_SINGLETON_CELO: ${{ secrets.TEST_SAFE_SINGLETON_CELO }}
  TEST_SAFE_PROXY_FACTORY_CELO: ${{ secrets.TEST_SAFE_PROXY_FACTORY_CELO }}

jobs:
  test:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: "Generate a fuzz seed that changes weekly to avoid burning through RPC allowance"
        run: >
          echo "FOUNDRY_FUZZ_SEED=$(
            echo $(($EPOCHSECONDS - $EPOCHSECONDS % 604800))
          )" >> $GITHUB_ENV

      - name: Run Forge tests
        run: make test
        id: test

      - name: "Add test summary"
        run: |
          echo "## Tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
